---
- name: Install requirements
  apt: 
    name: 
      - wget
      - python-psycopg2
    state: present

- name: Add PostgreSQL 11 keys
  shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

- name: Add PostgreSQL 11 to source list
  shell: echo deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main > /etc/apt/sources.list.d/postgresql.list

- name: Install PosgresSQL 11
  apt:
    name: postgresql-11
    state: present

- name: Check that PostgreSQL service is running
  service: name=postgresql state=started enabled=yes



