- name: Install nginx
  apt: 
    name: nginx
    state: present

- name: Create scheduler service
  ansible.builtin.copy:
    src: ~/ansible/files/default
    dest: /etc/nginx/sites-enabled/default

- name: Check that service Nginx is started
  ansible.builtin.service:
    name: nginx
    state: started


- name: Reload nginx
  shell: nginx -s reload